name: AdvancedKits
main: AdvancedKits\Main
version: 5.3.0
api: [3.0.0]
author: luca28pet
description: Add kits to your server
website: https://github.com/luca28pet/AdvancedKits
softdepend: [PiggyCustomEnchants]
commands:
 kit:
  description: Get a kit!
  usage: "/kit <kitName>"
  aliases: [ak, advancedkits]
  permission: advancedkits.command
 akreload:
  descrpition: Reload Kits settings
  usage: "/akreload"
  permission: advancedkits.admin
permissions:
 advancedkits:
  description: "Root permission"
  default: false
  children:
   advancedkits.command:
    description: "Allows the user to run /kit command"
    default: true
   advancedkits.admin:
    description: "Allows to manage admin features"
    default: op
